name: Health Check and OCI Instance Restart

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual execution

env:
  OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
  OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY_FILE }}

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup OCI CLI
      run: |
        # Download the installer script first
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install-oci-cli.sh
        # Then run it with the accept flag
        bash install-oci-cli.sh --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Configure OCI CLI
      run: |
        mkdir -p ~/.oci
        # Create config file
        cat > ~/.oci/config << EOF
        [DEFAULT]
        user=$OCI_CLI_USER
        fingerprint=$OCI_CLI_FINGERPRINT
        tenancy=$OCI_CLI_TENANCY
        region=$OCI_CLI_REGION
        key_file=~/.oci/oci_api_key.pem
        EOF
        
        # Create private key file
        echo "$OCI_CLI_KEY_CONTENT" > ~/.oci/oci_api_key.pem
        chmod 600 ~/.oci/oci_api_key.pem

    - name: Verify OCI Configuration
      run: oci --version

    - name: Run Health Check Script
      run: |
        chmod +x health-check.sh
        ./health-check.sh
      env:
        NODE1_INSTANCE_ID: ${{ var.NODE1_INSTANCE_ID }}
        NODE2_INSTANCE_ID: ${{ secrets.NODE2_INSTANCE_ID }}

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: healthcheck-logs
        path: logs/