name: Health Check and OCI Instance Restart

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup OCI CLI
      run: |
        # Instalar OCI CLI usando pip (mais confiável)
        pip install oci-cli
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run Health Check Script (com variáveis de ambiente OCI)
      run: |
        chmod +x health-check.sh
        ./health-check.sh
      env:
        NODE1_INSTANCE_ID: ${{ secrets.NODE1_INSTANCE_ID }}
        NODE2_INSTANCE_ID: ${{ secrets.NODE2_INSTANCE_ID }}
        # Variáveis de ambiente para autenticação OCI
        OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
        OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
        OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
        OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
        OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY_FILE }}

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: healthcheck-logs
        path: logs/