name: Health Check and OCI Instance Restart

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OCI CLI and Key
        run: |
          echo "Instalando OCI CLI..."
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install-oci-cli.sh
          bash install-oci-cli.sh --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

          echo "Creating OCI config and key files..."
          mkdir -p ~/.oci

          # Create the OCI config file using a "here document".
          # The final EOF must not be indented.
          cat > ~/.oci/config <<'EOF'
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          key_file=~/.oci/oci_api_key.pem
          EOF

          echo "${{ secrets.OCI_KEY_FILE }}" > ~/.oci/oci_api_key.pem

          chmod 600 ~/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config

      - name: Verify OCI Configuration
        run: |
          oci --version
          oci iam region list

      - name: Run Health Check Script
        run: |
          chmod +x health-check.sh
          ./health-check.sh
        env:
          # Use GitHub repository variables for non-sensitive data like instance IDs.
          NODE1_INSTANCE_ID: ${{ vars.NODE1_INSTANCE_ID }}
          NODE2_INSTANCE_ID: ${{ vars.NODE2_INSTANCE_ID }}

      - name: Upload Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: healthcheck-logs
          path: logs/

      - name: Debug - Verify OCI Files
        if: always() # Run this step even if previous steps fail
        run: |
          echo "Conteúdo do arquivo de configuração:"
          cat ~/.oci/config
          echo -e "\nPrimeiras linhas do arquivo de chave:"
          head -5 ~/.oci/oci_api_key.pem
          echo -e "\nPermissões dos arquivos:"
          ls -la ~/.oci/