name: Health Check and OCI Instance Restart

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:        # Allows manual execution

jobs:
  health-check:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
      OCI_CLI_KEY_FILE: /home/runner/.oci/oci_api_key.pem
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup OCI CLI and Key
      run: |
        echo "Installing OCI CLI..."
        curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install-oci-cli.sh
        bash install-oci-cli.sh --accept-all-defaults
        echo "$HOME/bin" >> $GITHUB_PATH

        echo "Creating OCI directory and files..."
        mkdir -p ~/.oci

        # Create config file with proper formatting
        cat > ~/.oci/config << EOF
[DEFAULT]
user=${{ secrets.OCI_USER_OCID }}
fingerprint=${{ secrets.OCI_FINGERPRINT }}
tenancy=${{ secrets.OCI_TENANCY_OCID }}
region=${{ secrets.OCI_REGION }}
key_file=/home/runner/.oci/oci_api_key.pem
EOF

        # Create private key file
        echo "${{ secrets.OCI_KEY_FILE }}" > /home/runner/.oci/oci_api_key.pem
        
        # Fix permissions
        chmod 600 /home/runner/.oci/oci_api_key.pem
        chmod 600 ~/.oci/config

        # Add OCI_API_KEY label to suppress warning
        echo "OCI_API_KEY" >> /home/runner/.oci/oci_api_key.pem

    - name: Verify OCI Configuration
      run: |
        oci --version
        oci iam region list

    - name: Run Health Check Script
      run: |
        chmod +x health-check.sh
        ./health-check.sh
      env:
        NODE1_INSTANCE_ID: ${{ secrets.NODE1_INSTANCE_ID }}
        NODE2_INSTANCE_ID: ${{ secrets.NODE2_INSTANCE_ID }}

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: healthcheck-logs
        path: logs/
    - name: Debug - Check OCI Files
      run: |
        echo "Config file content:"
        cat ~/.oci/config
        echo -e "\nKey file content (first few lines):"
        head -5 /home/runner/.oci/oci_api_key.pem
        echo -e "\nKey file permissions:"
        ls -la /home/runner/.oci/