name: Health Check and OCI Instance Restart

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    # Adicione o nome do seu ambiente aqui.
    # Isso é crucial para que o workflow possa acessar os 'Environment secrets'.
    environment: github-pages
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Validate Secrets
      run: |
        if [ -z "${{ secrets.OCI_KEY_FILE }}" ]; then
          echo "ERRO: O secret OCI_KEY_FILE não está configurado no repositório."
          echo "Por favor, adicione o conteúdo da sua chave privada OCI a este secret."
          exit 1
        fi

    - name: Setup OCI CLI
      run: |
        # Instalar OCI CLI usando pip (mais confiável)
        pip install oci-cli
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Run Health Check Script (com variáveis de ambiente OCI)
      run: |
        chmod +x health-check.sh
        ./health-check.sh
      env:
        # Corrigido para usar 'secrets' conforme sua configuração atual.
        # RECOMENDAÇÃO: Mova estes para 'Variables' no seu ambiente para melhor prática.
        NODE1_INSTANCE_ID: ${{ secrets.NODE1_INSTANCE_ID }}
        NODE2_INSTANCE_ID: ${{ secrets.NODE2_INSTANCE_ID }}
        # Variáveis de ambiente para autenticação OCI
        # Corrigido para corresponder aos nomes dos seus secrets.
        OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
        OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
        OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
        OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY_FILE }}

    - name: Upload Logs on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: healthcheck-logs
        path: logs/