permissions:
  contents: write # 1. Permissão CORRIGIDA para permitir 'git push'
name: Health Check & Restart

# Controls when the action will run. This is set to run on a schedule using cron syntax.
on:
  schedule:
    - cron: "*/5 * * * *" # Executa a cada 5 minutos
  workflow_dispatch: # Permite acionamento manual

jobs:
  health_check_job:
    runs-on: ubuntu-latest  # Specifies the type of virtual host machine to run the job on.
    name: Check all sites
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 2. Necessário para 'git pull --rebase' funcionar corretamente

      - name: Run Health Check Script
        id: health_check_script_run
        run: bash ./health-check.sh
        env:
          # 3. Lógica de reinício REMOVIDA daqui e movida para o script.
          #    As credenciais agora são passadas para o script usar.
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
          # O script espera a variável OCI_INSTANCE_ID.
          # Estou usando NODE1_INSTANCE_ID, ajuste se precisar reiniciar outra instância.
          NODE1_INSTANCE_ID: ${{ secrets.NODE1_INSTANCE_ID }}
