name: Health Check and OCI Instance Restart

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_USER_OCID }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_TENANCY_OCID }}
      OCI_CLI_REGION: ${{ secrets.OCI_REGION }}
      OCI_CLI_KEY_FILE: /home/runner/.oci/oci_api_key.pem

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup OCI CLI and Key
        run: |
          echo "Instalando OCI CLI..."
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh -o install-oci-cli.sh
          bash install-oci-cli.sh --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH

          echo "Criando diretório e arquivos OCI..."
          mkdir -p ~/.oci

          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=${{ secrets.OCI_USER_OCID }}
          fingerprint=${{ secrets.OCI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_TENANCY_OCID }}
          region=${{ secrets.OCI_REGION }}
          EOF
          key_file=/home/runner/.oci/oci_api_key.pem
          EOF

          echo "${{ secrets.OCI_KEY_FILE }}" > /home/runner/.oci/oci_api_key.pem

          chmod 600 /home/runner/.oci/oci_api_key.pem
          chmod 600 ~/.oci/config

      - name: Verificar configuração OCI
        run: |
          oci --version
          oci iam region list

      - name: Executar script de Health Check
        run: |
          chmod +x health-check.sh
          ./health-check.sh
        env:
          NODE1_INSTANCE_ID: ${{ secrets.NODE1_INSTANCE_ID }}
          NODE2_INSTANCE_ID: ${{ secrets.NODE2_INSTANCE_ID }}

      - name: Upload dos logs em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: healthcheck-logs
          path: logs/

      - name: Debug - Verificar arquivos OCI
        run: |
          echo "Conteúdo do arquivo de configuração:"
          cat ~/.oci/config
          echo -e "\nPrimeiras linhas do arquivo de chave:"
          head -5 /home/runner/.oci/oci_api_key.pem
          echo -e "\nPermissões dos arquivos:"
          ls -la /home/runner/.oci/